urls:
- category: Hybrid (Dynamic Asset Allocation)
  name: HDFC Balanced Advantage Fund
  url: https://groww.in/mutual-funds/hdfc-balanced-advantage-fund-direct-growth
- category: Index Fund (Large-cap)
  name: HDFC BSE Sensex Index Fund
  url: https://groww.in/mutual-funds/hdfc-bse-sensex-index-fund-direct-growth
- category: Debt (Corporate Bond)
  name: HDFC Corporate Bond Fund
  url: https://groww.in/mutual-funds/hdfc-medium-term-opportunities-fund-direct-growth
- category: Flexi-cap
  name: HDFC Flexi Cap Fund
  url: https://groww.in/mutual-funds/hdfc-equity-fund-direct-growth
- category: Fund of Fund (Commodity)
  name: HDFC Gold ETF Fund of Fund
  url: https://groww.in/mutual-funds/hdfc-gold-etf-fund-of-fund-direct-plan-growth
- category: Hybrid (Debt-oriented)
  name: HDFC Hybrid Debt Fund
  url: https://groww.in/mutual-funds/hdfc-monthly-i-come-plan-long-term-plan-direct-growth
- category: Mid-cap
  name: HDFC Mid Cap Fund
  url: https://groww.in/mutual-funds/hdfc-mid-cap-fund-direct-growth
- category: Multi-cap
  name: HDFC Multi Cap Fund
  url: https://groww.in/mutual-funds/hdfc-multi-cap-fund-direct-growth
- category: Index Fund (Large-cap)
  name: HDFC Nifty50 Equal Weight Index Fund
  url: https://groww.in/mutual-funds/hdfc-nifty50-equal-weight-index-fund-direct-growth
- category: Index Fund (Large-cap)
  name: HDFC Nifty 50 Index Fund
  url: https://groww.in/mutual-funds/hdfc-nifty-50-index-fund-direct-growth
- category: Index Fund (Large-cap)
  name: HDFC Nifty Top 20 Equal Weight Index Fund
  url: https://groww.in/mutual-funds/hdfc-nifty-top-20-equal-weight-index-fund-direct-growth
- category: Sectoral (Equity)
  name: HDFC Pharma and Healthcare Fund
  url: https://groww.in/mutual-funds/hdfc-pharma-and-healthcare-fund-direct-growth
- category: Debt (Short Duration)
  name: HDFC Short Term Debt Fund
  url: https://groww.in/mutual-funds/hdfc-short-term-opportunities-fund-direct-growth
- category: Fund of Fund (Commodity)
  name: HDFC Silver ETF FOF
  url: https://groww.in/mutual-funds/hdfc-silver-etf-fof-direct-growth
- category: Small-cap
  name: HDFC Small Cap Fund
  url: https://groww.in/mutual-funds/hdfc-small-cap-fund-direct-growth
