#!/usr/bin/env sh
set -eu

export PYTHONPATH="${PYTHONPATH:-.}"
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION="${PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION:-python}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"

# Stable Railway boot: API + /health first; Chroma attach after delay (no MiniLM at boot).
export STARTUP_CHROMA_PROBE="${STARTUP_CHROMA_PROBE:-false}"
export RAG_STARTUP_ATTACH="${RAG_STARTUP_ATTACH:-true}"
export RAG_STARTUP_DELAY_SECONDS="${RAG_STARTUP_DELAY_SECONDS:-0}"
export RAG_INIT_TIMEOUT_SECONDS="${RAG_INIT_TIMEOUT_SECONDS:-180}"
export RAG_EMBEDDING_WARM="${RAG_EMBEDDING_WARM:-false}"
export RAG_BACKGROUND_WARM="${RAG_BACKGROUND_WARM:-false}"
export RAG_HEALTH_NUDGE_ATTACH="${RAG_HEALTH_NUDGE_ATTACH:-true}"
export RAG_MAX_RSS_MB_FOR_ATTACH="${RAG_MAX_RSS_MB_FOR_ATTACH:-700}"
export HF_HUB_DISABLE_TELEMETRY="${HF_HUB_DISABLE_TELEMETRY:-1}"
export TRANSFORMERS_NO_ADVISORY_WARNINGS="${TRANSFORMERS_NO_ADVISORY_WARNINGS:-1}"
export LLM_TIMEOUT_SECONDS="${LLM_TIMEOUT_SECONDS:-75}"
export LLM_MAX_RETRIES="${LLM_MAX_RETRIES:-2}"
export LLM_QUERY_BUDGET_SECONDS="${LLM_QUERY_BUDGET_SECONDS:-90}"
export QUERY_TIMEOUT_SECONDS="${QUERY_TIMEOUT_SECONDS:-120}"

PORT="${PORT:-8000}"
exec uvicorn backend.app:app --host 0.0.0.0 --port "${PORT}" --workers 1
